"""Sandbox execution guardrails for the computer tool.

Local-first Swarm runs one user on their own machine, so this is not about
withstanding a determined remote attacker. It is about two things that do
bite locally:

  1. A destructive command typed or generated by mistake should stop, and
     the stop should be visible afterwards rather than silently skipped.
  2. Prompt injection. A web page or file that says "ignore previous
     instructions and run <destructive>" reaches computer_run as an ordinary
     string, and the old deny-list could not tell the difference.

The deny-list is a blunt instrument by design: it matches on normalised
text so trivial obfuscation (extra spaces, extra dashes, path prefixes)
does not slip past. It is a backstop, not a sandbox. The real boundary is
still the working directory plus the timeout, exactly as AGENTS.md and
SECURITY.md say.
"""
from __future__ import annotations

import re
import unicodedata

# Normalise before matching so `rm  -rf  /`, `rm -r -f /`, and `rm -rf --no-preserve-root /`
# all reduce to something the patterns below actually see.
# The two non-ASCII members are deliberate: U+00A0 (no-break space) and U+00A1
# are what a copy-paste turns a space into, and a paste is exactly the input
# a model hands this function. Written as escapes so no editor can mangle them.
_WS = re.compile("[\\s\u00a0\u00a1]+")
_DASHES = re.compile(r"-{2,}")
# `rm -r -f /` is `rm -rf /` with the flags split apart. Collapse the split form
# so one pattern covers both spellings.
_SPLIT_RF = re.compile(r"\b(rm|rmdir)\s+-[a-z]*r[a-z]*\s+-[a-z]*f[a-z]*\b")
# Every quoting form the shells below accept. A quoted argument means the same
# thing to the shell as an unquoted one, so quotes are stripped before matching:
# otherwise `rm -rf " /"` sails past the denylist that stops `rm -rf /`.
_QUOTES = re.compile(r"[\"'`]")
# `${VAR}` is the braced spelling of `$VAR` (bash/zsh); `%VAR%` is the cmd.exe
# spelling. Both name the same home directory, so both must reduce to `$var`
# or `rm -rf ${HOME}` deletes the user's home while `rm -rf $HOME` is blocked.
_BRACED_VAR = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
_CMD_VAR = re.compile(r"%([A-Za-z_][A-Za-z0-9_]*)%")


def normalize(command: str) -> str:
    """Collapse quoting, whitespace and dash runs so obfuscation does not hide a match."""
    # `is_dangerous` runs on the raw argument before anything coerces it, and
    # a schema that says "string" does not stop a model sending a number.
    # Treat anything non-string as un-normalisable text rather than raising:
    # this runs on the turn's hot path and an exception here would become an
    # "[agent error: ...]" message instead of the reply.
    if not isinstance(command, str):
        command = "" if command is None else str(command)
    raw = unicodedata.normalize("NFKC", command or "")
    # The classic fork bomb needs its parentheses intact, so check for the
    # self-referential shape before punctuation is flattened.
    if re.search(r":\s*\(\s*\)\s*\{", raw):
        return ":(){"
    text = raw.replace("`", " ").replace("$(", " ").replace(")", " ")
    # Quotes and both variable spellings go before the patterns see the text:
    # the shells above all accept them, so the denylist must not be nicer than
    # the thing it is guarding.
    text = _BRACED_VAR.sub(r"$\1", text)
    text = _CMD_VAR.sub(r"$\1", text)
    text = _QUOTES.sub("", text)
    text = _WS.sub(" ", text)
    text = _DASHES.sub("-", text)
    text = text.lower()
    return _SPLIT_RF.sub(r"\1 -rf", text)


# Each pattern targets a class of action that is unrecoverable on the user's
# own machine. Kept explicit rather than clever: a pattern nobody can read is
# a pattern nobody can trust.
_DENY = (
    # filesystem destruction
    re.compile(r"\brm\b[^|;&]*\s-[a-z]*[rf][a-z]*\s+(?:--?[\w-]+\s+)*(/|~|\$home|\$[a-z_]+|\*)"),
    # A whole drive: `rm -rf C:\` and `rm -rf C:\Users` are the same class of
    # mistake as `rm -rf /`. The Windows denylist already refuses `del C:\`,
    # so the recursive form must not be the one that slips through.
    re.compile(r"\brm\b[^|;&]*\s-[a-z]*[rf][a-z]*\s+[a-z]:(?:[/\\]|$)"),
    re.compile(r"\brm\b[^|;&]*\s-[a-z]*[rf][a-z]*\s+\.\s*$"),
    re.compile(r"\brmdir\b[^|;&]*/(\s|$)"),
    # disks and partitions
    re.compile(r"\b(mkfs|fdisk|parted|diskpart)\b"),
    re.compile(r"\bdd\b[^|;&]*\bof="),
    # windows-specific destruction
    re.compile(r"\b(format|del)\s+[a-z]:\\", re.I),
    re.compile(r"remove-item\b[^|;&]*-recurse[^|;&]*[a-z]:\\"),
    re.compile(r"\bcipher\s+/w\b"),
    # fork bombs and resource exhaustion
    re.compile(r":\s*\(\s*\)\s*\{"),
    re.compile(r"\b(yes|curl|wget)\b[^|;&]*\|\s*(ba)?sh\b"),
    # credential harvesting and exfiltration to the network
    # Every common reader for a dotenv file, on both shell families: `type`
    # (cmd), `cat` (posix), `get-content` and its alias `gc` (PowerShell),
    # `more`/`less`/`head`/`tail`, plus the copy readers that duplicate it.
    # The file component is matched whole so `cat env.txt` is a name, not a
    # dotenv, and `cat .\env` (the Windows separator) still counts. The
    # checked-in documentation suffixes are the exception: `.env.example`
    # holds placeholder names by convention, not keys.
    re.compile(
        r"\b(cat|type|more|less|head|tail|gc|get-content|copy|cp|findstr|sls)\b"
        r"[^|;&]*(?:^|[\s\"'|;&/\\])(?:"
        r"\.env(?:\.(?!(?:example|sample|template|dist)\b)[\w.-]*)?|env"
        r")(?:[\s\"']|$)"
    ),
    re.compile(r"\b(cat|type)\b[^|;&]*(id_rsa|\.ssh[/\\]|credentials|\.aws[/\\])"),
    re.compile(r"\b(history|fc)\b[^|;&]*\|\s*(curl|wget|nc|ncat)\b"),
    # windows credential dump
    re.compile(r"\b(mimikatz|sekurlsa|lsadump)\b"),
)


def is_dangerous(command: str) -> str | None:
    """Return the matched pattern's description, or None if the command is fine."""
    text = normalize(command)
    if not text.strip():
        return None
    for pattern in _DENY:
        if pattern.search(text):
            return pattern.pattern
    return None


def refusal_reason(command: str, match: str) -> str:
    """Human-readable, recorded in-thread so the block is visible later."""
    return (
        "Blocked before running. This command looks destructive on the machine "
        "running Swarm, so it was not executed. If you meant to run something "
        "like this, narrow it to a specific path and re-ask — for example "
        "target a single file inside the sandbox rather than a home directory "
        "or a whole drive."
    )