"""Sandbox execution guardrails for the computer tool.

Local-first Swarm runs one user on their own machine, so this is not about
withstanding a determined remote attacker. It is about two things that do
bite locally:

  1. A destructive command typed or generated by mistake should stop, and
     the stop should be visible afterwards rather than silently skipped.
  2. Prompt injection. A web page or file that says "ignore previous
     instructions and run <destructive>" reaches computer_run as an ordinary
     string, and the old deny-list could not tell the difference.

The deny-list is a blunt instrument by design: it matches on normalised
text so trivial obfuscation (extra spaces, extra dashes, path prefixes)
does not slip past. It is a backstop, not a sandbox. The real boundary is
still the working directory plus the timeout, exactly as AGENTS.md and
SECURITY.md say.
"""
from __future__ import annotations

import re
import unicodedata

# Normalise before matching so `rm  -rf  /`, `rm -r -f /`, and `rm -rf --no-preserve-root /`
# all reduce to something the patterns below actually see.
_WS = re.compile(r"[\s ]+")
_DASHES = re.compile(r"-{2,}")
# `rm -r -f /` is `rm -rf /` with the flags split apart. Collapse the split form
# so one pattern covers both spellings.
_SPLIT_RF = re.compile(r"\b(rm|rmdir)\s+-[a-z]*r[a-z]*\s+-[a-z]*f[a-z]*\b")


def normalize(command: str) -> str:
    """Collapse whitespace and dash runs so obfuscation does not hide a match."""
    raw = unicodedata.normalize("NFKC", command or "")
    # The classic fork bomb needs its parentheses intact, so check for the
    # self-referential shape before punctuation is flattened.
    if re.search(r":\s*\(\s*\)\s*\{", raw):
        return ":(){"
    text = raw.replace("`", " ").replace("$(", " ").replace(")", " ")
    text = _WS.sub(" ", text)
    text = _DASHES.sub("-", text)
    text = text.lower()
    return _SPLIT_RF.sub(r"\1 -rf", text)


# Each pattern targets a class of action that is unrecoverable on the user's
# own machine. Kept explicit rather than clever: a pattern nobody can read is
# a pattern nobody can trust.
_DENY = (
    # filesystem destruction
    re.compile(r"\brm\b[^|;&]*\s-[a-z]*[rf][a-z]*\s+(?:--?[\w-]+\s+)*(/|~|\$home|\*)"),
    re.compile(r"\brm\b[^|;&]*\s-[a-z]*[rf][a-z]*\s+\.\s*$"),
    re.compile(r"\brmdir\b[^|;&]*/(\s|$)"),
    # disks and partitions
    re.compile(r"\b(mkfs|fdisk|parted|diskpart)\b"),
    re.compile(r"\bdd\b[^|;&]*\bof="),
    # windows-specific destruction
    re.compile(r"\b(format|del)\s+[a-z]:\\", re.I),
    re.compile(r"remove-item\b[^|;&]*-recurse[^|;&]*[a-z]:\\"),
    re.compile(r"\bcipher\s+/w\b"),
    # fork bombs and resource exhaustion
    re.compile(r":\s*\(\s*\)\s*\{"),
    re.compile(r"\b(yes|curl|wget)\b[^|;&]*\|\s*(ba)?sh\b"),
    # credential harvesting and exfiltration to the network
    re.compile(r"\b(cat|type|get-content)\b[^|;&]*\.env\b"),
    re.compile(r"\b(cat|type)\b[^|;&]*(id_rsa|\.ssh[/\\]|credentials|\.aws[/\\])"),
    re.compile(r"\b(history|fc)\b[^|;&]*\|\s*(curl|wget|nc|ncat)\b"),
    # windows credential dump
    re.compile(r"\b(mimikatz|sekurlsa|lsadump)\b"),
)


def is_dangerous(command: str) -> str | None:
    """Return the matched pattern's description, or None if the command is fine."""
    text = normalize(command)
    if not text.strip():
        return None
    for pattern in _DENY:
        if pattern.search(text):
            return pattern.pattern
    return None


def refusal_reason(command: str, match: str) -> str:
    """Human-readable, recorded in-thread so the block is visible later."""
    return (
        "Blocked before running. This command looks destructive on the machine "
        "running Swarm, so it was not executed. If you meant to run something "
        "like this, narrow it to a specific path and re-ask — for example "
        "target a single file inside the sandbox rather than a home directory "
        "or a whole drive."
    )